version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: bookhive-mysql
    restart: always
    environment:
      MYSQL_DATABASE: bmd_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: bookhive
      MYSQL_PASSWORD: bookhive123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: bookhive-app
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bmd_db
      SPRING_DATASOURCE_USERNAME: bookhive
      SPRING_DATASOURCE_PASSWORD: bookhive123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

volumes:
  mysql_data:
