name: Build and deploy Java project to Azure Function App - bookhive

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: bookhive  # your Azure Function App name
  PACKAGE_DIRECTORY: 'bookhive'     # points to backend folder
  JAVA_VERSION: '17'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build backend with Maven
        run: |
          cd ${{ env.PACKAGE_DIRECTORY }}
          mvn clean package

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EA704170400D48F7A5AED02485E5A582 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1539230A19C347A1AB7500F65A0FDD72 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_681A794CE7B54C15B34313A5FA3F9194 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          slot-name: Production
          package: ${{ env.PACKAGE_DIRECTORY }}
          respect-pom-xml: true
